### ISSUE TITLE
[Bug] Ignores moduleNameMapper in .jestrc.json

### ISSUE THREAD

**Issue by presidenten** [Raathigesh/majestic#100]
## Version Info

- Version of Majestic: 1.2.23
- Version of Jest: 24.1.0
- Version of Rollup: 1.4.0
- Version of Node: 10.15.3
- Operating System: Osx 10.14.3

## Reproduction Repo
https://github.com/presidenten/wdio-video-reporter/

## To reproduce
Clone repo
- yarn install
- yarn test (all tests pass)
- majestic (index.spec.js does not run)
![image](https://user-images.githubusercontent.com/3883897/55382245-7c5aff00-5525-11e9-8e05-b1088bb88478.png)

## Note
In .jestrc.json all pictures are mapped to a filemock in __mocks__.

**Comment by Raathigesh** [comment]
Could you add the following to package.json and check again?

```
 "majestic": {
    "args": [
      "--config=.jestrc.json"
    ]
  }
```

https://github.com/Raathigesh/majestic#optional-configuration

**Comment by presidenten** [comment]
Sorry! Totally forgot to test.

It works when I add it to my `package.json`.

Closing the issue.
