### ISSUE TITLE
Better examples

### ISSUE THREAD

**Issue by silverHub** [Raathigesh/majestic#102]
## Is this a bug report or a feature request?

feature request (?)
Better examples needed, for me it is not evident how to pass additional arguments to jest in package.json config.
For instance the most basic: how to pass the jest config file.

```
"majestic": {
  args: [   ],  // in what format?

}

``` 

## Version Info

- Version of Majestic: 1.2.24
- Version of Jest: 23.6.0
- Version of Node: v8.11.3
- Operating System: Win7

**Comment by Raathigesh** [comment]
Just like you would pass in a terminal but here as comm separated array items.
```
"majestic": {
  args: ["--config=./path/to/your/config.json"], 
}
```

**Comment by silverHub** [comment]
Thanks, that worked. However to nitpick a bit, in the example the syntax is wrong, as we are talking about a json file you need to have string for keys:
"majestic": {
  "args": [...]
}

**Comment by Raathigesh** [comment]
The readme could be better. Would you like to send a PR to improve it?
