### ISSUE TITLE
CRA failure when using custom react scripts

### ISSUE THREAD

**Issue by moos** [Raathigesh/majestic#103]
## Is this a bug report or a feature request?

Feature/Bug

## Version Info

- Version of Majestic: Majestic v1.2.23
- Version of Jest: 23.6.0
- Version of Node: v8.12.0
- Operating System: macOS 10.13.6

## Reproduction Repo

If one is using [custom-react-scripts](https://github.com/kitze/custom-react-scripts/), or a variation, in a Create React App project, it fails to find the test scripts.

`TypeError: Cannot read property 'projectRoot' of undefined`

The function `getJestScriptForCreateReactApp` is hard-coded to only look for `react-scripts`.

Temp workaround (at project root):
```
$ ln -s ../node_modules/custom-react-scripts  node_modules/react-scripts
```

**Comment by Raathigesh** [comment]
You could manually specify the jest script for `custom-react-scripts` through the [package.json configuration](https://github.com/Raathigesh/majestic#optional-configuration) and make it work. is that good enough?

**Comment by moos** [comment]
That didn't work -- because it's a CRA, it takes a different path in the code and doesn't look at `jestScriptPath`.  But that's a good way to go about it -- I'll submit a PR shortly for review.
