### ISSUE TITLE
Add support for multiple jest runners in one project

### ISSUE THREAD

**Issue by MacZel** [Raathigesh/majestic#114]
Suppose having different jest configs for unit and e2e tests. Whenever running tests in majestic GUI majestic config in `package.json` has to be changed.
How about switching from:
```js
"majestic": {
    "jestScriptPath": "./node_modules/jest/bin/jest.js",
    "args": ["--config=./config/jest/e2e.json"]
}
```
to something like this:
```js
"majestic": {
    "jestScriptPath": "./node_modules/jest/bin/jest.js",
    "runners": {
        "unit": ["--config=./config/jest/unit.json"],
        "e2e": ["--config=./config/jest/e2e.json"]
    }
}
```

**Comment by Raathigesh** [comment]
How about having named configs like below

```
"majestic": {
    "jestScriptPath": "./node_modules/jest/bin/jest.js",
    "configs": {
         "unit": {
             "args": [],
              "env": {}
          },
        "e2e": {
             "args": [],
              "env": {}
          }
     }
}
```

and then when starting Majestic you could pass a flag like `--config=unit`?

**Comment by MacZel** [comment]
That's exactly what I meant

**Comment by Raathigesh** [comment]
Would you be interested in contributing this enhancement? We can do this by updating the [config-resolver](https://github.com/Raathigesh/majestic/blob/master/server/services/config-resolver.ts).

**Comment by MacZel** [comment]
Yup, would love to contribute

**Comment by Raathigesh** [comment]
Awesome. Feel free to ping me if you run into any issues. Would be happy to help!
