### ISSUE TITLE
All tests filtered by 'only failed tests' option

### ISSUE THREAD

**Issue by robotanz** [Raathigesh/majestic#115]
## Is this a bug report or a feature request?

A bug

## Version Info

- Version of Majestic: 1.3.0

## Reproduction

- Run all tests with some failing tests
- Filter the test tree to display only failing tests
- Fix the code, so the test passes...
- Since all tests are now passing, no test is displayed in the side bar and there's no button to display them again

**Comment by Raathigesh** [comment]
I bumped into this as well. Will fix it 👍

**Comment by briwa** [comment]
I've bumped to this issue as well, I could take a look this weekend if you're not already working on this @Raathigesh

**Comment by Raathigesh** [comment]
You are very welcome to take a look  👍 Thank you for helping out.
