### ISSUE TITLE
Coverage should respect coverageDirectory config option

### ISSUE THREAD

**Issue by aantipov** [Raathigesh/majestic#116]
## Is this a bug report or a feature request?

A bug report

## Version Info

- Version of Majestic: 1.3.0
- Version of Jest: 24.7.0
- Version of Node: 8.11.3
- Operating System: MacOS 10.14.4

## Reproduction Repo

I installed the new 1.3.0 of majestic.
But running a command `node ./node_modules/.bin/majestic --version` gives
```
v1.2.24
```

File `node_modules/majestic/package.json` contains correct version
```
  "_from": "majestic",
  "_id": "majestic@1.3.0",
```

In the file `node_modules/majestic/dist/server/index.js` at line 159070 I found 
```js
/* 1006 */
/***/ (function(module) {

module.exports = {"name":"majestic","version":"1.2.24","engines":{"node":">=7.10.1"},"main":"index.js","license":"MIT","scripts":{"ui":"webpack-dev-server --env.development --config ./scripts/webpack.ui.config.js","server":"ts-node  --project ./tsconfig.server.json ./server/index.ts","build-server":"cross-env BABEL_ENV='production' webpack --env.production --config ./scripts/webpack.server.config.js","build-ui":"cross-env BABEL_ENV='production' rimraf dist && webpack --env.production --config ./scripts/webpack.ui.config.js","prod":"npm run build-ui && npm run build-server","watch-server":"nodemon","ship":"npm run prod && np --yolo","integration":"cd ./integration && yarn run-in-ci"},"dependencies":{"node-fetch":"^2.3.0","open":"^6.0.0","read-pkg-up":"^4.0.0"},"devDependencies":{"@babel/core":"^7.1.2","@babel/parser":"^7.2.3","@babel/plugin-proposal-class-properties":"^7.0.0","@babel/plugin-proposal-decorators":"^7.1.2","@babel/plugin-proposal-object-rest-spread":"^7.0.0","@babel/polyfill":"^7.0.0","@babel/preset-env":"^7.0.0","@babel/preset-react":"^7.0.0","@babel/preset-typescript":"^7.0.0","@babel/traverse":"^7.2.3","@types/babel-traverse":"^6.25.4","@types/chokidar":"^1.7.5","@types/express":"^4.16.0","@types/istanbul-lib-coverage":"^2.0.0","@types/istanbul-lib-source-maps":"^1.2.1","@types/react":"^16.8.6","@types/react-dom":"^16.8.2","@types/react-split-pane":"^0.1.67","@types/styled-components":"^4.1.4","@types/styled-system":"^3.1.0","ansi-to-html":"^0.6.10","apollo-client":"^2.3.8","apollo-client-preset":"^1.0.8","apollo-link":"^1.2.3","apollo-link-ws":"^1.0.9","apollo-utilities":"^1.0.21","awesome-typescript-loader":"^5.2.1","babel-loader":"^8.0.2","babel-plugin-styled-components":"^1.8.0","body-parser":"^1.18.3","chokidar":"^2.0.4","chrome-launcher":"^0.10.5","consola":"^2.5.7","copy-webpack-plugin":"^5.0.1","cross-env":"^5.2.0","css-loader":"^1.0.0","file-loader":"^3.0.1","get-port":"^4.2.0","graphql-tag":"^2.9.2","graphql-yoga":"^1.16.1","html-webpack-include-assets-plugin":"^1.0.5","html-webpack-plugin":"^3.2.0","html-webpack-template":"^6.2.0","istanbul-lib-coverage":"^2.0.3","istanbul-lib-source-maps":"^3.0.2","launch-editor":"^2.2.1","lodash.throttle":"^4.1.1","minimist":"^1.2.0","nanoid":"^2.0.0","nodemon":"^1.18.3","np":"^4.0.2","react":"^16.8.3","react-apollo":"^2.1.11","react-apollo-hooks":"^0.2.1","react-dom":"^16.8.3","react-feather":"^1.1.4","react-inspector":"^3.0.0","react-split-pane":"^0.1.84","react-spring":"^8.0.9","react-tippy":"^1.2.3","react-virtualized-auto-sizer":"^1.0.2","react-window":"^1.6.2","reflect-metadata":"^0.1.12","resolve-pkg":"^1.0.0","rimraf":"^2.6.2","style-loader":"^0.23.0","styled-components":"^4.1.3","styled-system":"^3.1.11","svg-inline-loader":"^0.8.0","svg-react-loader":"^0.4.5","ts-node":"^7.0.1","type-graphql":"^0.14.0","typeface-open-sans":"^0.0.54","typescript":"^3.0.1","uglifyjs-webpack-plugin":"^2.0.0","url-loader":"^1.1.1","webpack":"^4.17.1","webpack-cli":"^3.1.0","webpack-dev-server":"^3.2.1"},"resolutions":{"graphql":"^0.13.0"},"bin":{"majestic":"./dist/server/index.js"},"files":["/dist/**","/yarn.lock"]};
```

Therefore it looks like dist files were not updated in the `1.3.0` release

**Comment by Raathigesh** [comment]
The dist files are correct but it's the package.json was required and bundled before the publish task increases the version on the package file. 

This is a bug and should be fixed but the dist files are correct and contain the latest version.

**Comment by aantipov** [comment]
Hmm, but I can't see the "Collect coverage" button which should be included in 1.3.0 (according to the picture https://user-images.githubusercontent.com/3108160/55477280-699b1400-5664-11e9-8419-82dd1bb5d774.png)
Strange...

**Comment by Raathigesh** [comment]
That is strange. Are you using npx?

**Comment by aantipov** [comment]
I tried out different both options (npm run..., node node_modules/.bin/majestic, npx majestic), nothing works

**Comment by Raathigesh** [comment]
Could you please open `/dist/ui/ui.bundle.js` from the majestic installed location and search for the string `Collect coverage`? If it's there, then we have the correct bundle but something else is wrong. Could be browser cache?

**Comment by aantipov** [comment]
The string is there. But this "Collect coverage" button on top was in 1.2.24 version as well, right? 
I used Incognito mode, so it should not be a problem with browser cache.
What is the button next to "Refresh files"? How is it called? I'm looking for that button to open the Coverage report

**Comment by Raathigesh** [comment]
`Collect coverage` button was introduced in 1.3 and not before that. The button that's next to `Refresh files` only appears if there are [lcov reports which are generated by Jest exists](https://github.com/Raathigesh/majestic/blob/master/server/services/results.ts#L163)

**Comment by aantipov** [comment]
Ah, ok, I see now. 
I started using majestic 3 days ago and I thought it was 1.2.24 (because it reported itself as 1.2.24)
But now I realise that it was 1.3.0 already, because `Collect coverage` was there.

What I was looking for is `Show coverage report` button. This button didn't show up in my case and now I understand why: 
1. it should be `lcov` report only
2. I use a custom folder for the coverage-report (`coverageDirectory` setting in Jest config)

Thanks a lot for helping me with that! 👍 

Is it possible to respect this `coverageDirectory` Jest setting?

**Comment by Raathigesh** [comment]
Yes, We can enhance the feature to respect `coverageDirectory`. Will reopen this issue to track the enhancement.

**Comment by olavoparno** [comment]
@Raathigesh add another argument for custom coverageDirectory path e.g. --coverageDir="./custom-folder" using process.argv. What do you think about it?

**Comment by Raathigesh** [comment]
Hey @olavoparno 👋 ,

I was thinking to get the coverage directory from Jest itself (using the `--showConfig` flag).

**Comment by Raathigesh** [comment]
[1.4](https://github.com/Raathigesh/majestic/releases/tag/v1.4.0) is released with this enhancement. Please do test it and feel free to reopen if you run into issues.
