### ISSUE TITLE
🃏Add Tests

### ISSUE THREAD

**Issue by azz** [Raathigesh/majestic#12]
Unless I'm missing something there aren't any tests! I would recommend this great test runner called "Jest", you might have heard of it :wink:.

In all seriousness, the stack you've chosen has a great set of tooling such as:

- [`jest-styled-components`](https://github.com/styled-components/jest-styled-components)
- [`enzyme`](https://github.com/airbnb/enzyme)
- [`spectron`](https://github.com/electron/spectron)

These tools will make maintaining this project _much_ easier, especially when it comes to trusting code changes you haven't manually tested.

**Comment by Raathigesh** [comment]
Haha! Totally. I overlooked tests earlier so I can just get something out to see the feedback. As it turns out, people like the idea. Thanks for the pointers. I'll have to start writing tests soon.

**Comment by James-E-Adams** [comment]
Whilst we're having an iress party, I may be able to contribute some tests if I get some free time this weekend. Love the idea @Raathigesh - trying to get it hooked up to a project now. :)

**Comment by Raathigesh** [comment]
Awesome. Thank you!

**Comment by ddebarros** [comment]
@James-E-Adams  i'd also be interested in writing some tests for the renderer portion using spectron

**Comment by James-E-Adams** [comment]
Sure thing @ddebarros, that would be great. I'll look into some unit tests/basic sanity tests using enzyme and jest.

**Comment by ddebarros** [comment]
@James-E-Adams  is there a specific file structure you have in mind? I'm proposing something like this
```bash
├── src/
├── __tests__
│   ├── renderer
│    ├── renderer.test.tsx
│    └── renderer.test2.tsx
│   └── main
│    ├── main.test.tsx
│    └── main.test2.tsx
├── package.json
└── tsconfig.json

```

**Comment by James-E-Adams** [comment]
Nope, that's fine for now. Can always refactor later on.

**Comment by Raathigesh** [comment]
After so long, finally managed to get the rewrite almost done along with cypress integration tests. Unit tests are still lacking and should be added though :)

Closing this for now.
