### ISSUE TITLE
FR: Add Some Sort of GUI Notification when Majestic breaks and fatally errors.

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#121]
💡 Feature Request: Add some sort of GUI notification or warning when throwing a fatal error.

- Version of Majestic: 1.3.0
- Version of Jest: 20.0.3
- Version of Node: 8.15.1
- Operating System: macOS Mojave

When editing test files sometimes I have a syntax error. Due to Majestic watching for file changes, when there is a fatal syntax error in my tests/code Majestic will break and exit out of it's process. However the webpage is still visible and doesn't look like anything has changed. A nice feature I'd like to see is some sort of warning or error thrown when the script is errored out. Just a better error handler is all that is needed. Thanks!

For reference:

This is what I'm talking about when I say fatal syntax error:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/34947910/56043339-0c116200-5d0b-11e9-85df-96257fca1f3b.png">

**Comment by Raathigesh** [comment]
We do handle this better in [v1.4](https://github.com/Raathigesh/majestic/releases/tag/v1.4.0). Play with it and let me know.

**Comment by M4cs** [comment]
Yes much better handling now. Thank you @Raathigesh!

**Comment by M4cs** [comment]
Reopening because i thought this was an bug not a feature request

**Comment by M4cs** [comment]
Closed bc i realized this is implemented
