### ISSUE TITLE
[Bug] Can't get server running from source.

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#122]
Bug Report

- Version of Majestic: 1.3.0
- Version of Jest: 20.0.3
- Version of Node: 8.15.1
- Operating System: macOS Mojave

I am trying to help contribute by fixing one of the issues I created (#120). However when trying to start the server through VS Code, I get this error:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/34947910/56044516-54ca1a80-5d0d-11e9-941f-6a02483e08e7.png">

I tried also running from CLI with `yarn prod` and it closes without an error just warnings.

**Comment by M4cs** [comment]
I get the same error when running one instance of `yarn ui` and one of `yarn server`

**Comment by Raathigesh** [comment]
Thank you for trying to contribute.

could you please try commenting [this line](https://github.com/Raathigesh/majestic/blob/a2149375910c800e74c3bcb921d62302da8aaa00/server/index.ts#L36) and starting the server again?

**Comment by Raathigesh** [comment]
also when you start the server, the UI expects the server to run in Port 4000. And also please use the URL that the `yarn ui` gives you to view the UI.

**Comment by dangus21** [comment]
tried commenting that line, no i get this: 
![image](https://user-images.githubusercontent.com/3925278/56141230-53f6ea00-5f94-11e9-99a9-ff5e70698d3d.png)

**Comment by M4cs** [comment]
I commented that line and also got Cannot GET / now. The same issue as @dangus21. I have merged your recent changes into my fork as well and still get the error.

**Comment by M4cs** [comment]
Using port 9000 fixes the issue after adding jest to the node_modules
