### ISSUE TITLE
[Feat. Req.] Add Keyboard Shortcuts for Running Tests and Refreshing

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#124]
Feature Request 💡 

Add some keyboard shortcuts to east running tests quickly.

Ctrl + T - All Tests
Crtl + Enter - Single Test
Crtl + W - Watch Mode

Just an idea

**Comment by Raathigesh** [comment]
This is a good idea. We should do it.

**Comment by M4cs** [comment]
Any update on this?

**Comment by jsmey** [comment]
@Raathigesh, would you be ok with pulling in https://www.npmjs.com/package/react-hot-keys for this?

**Comment by Raathigesh** [comment]
@jsmey I would go with https://github.com/greena13/react-hotkeys since it seems comparatively well documented? Am I missing something?

**Comment by jsmey** [comment]
I don't have a preference. I can give this a try.

**Comment by Raathigesh** [comment]
@jsmey Also, Thank you for all the contributions you are making recently. Appreciate the help very much.

**Comment by jsmey** [comment]
@Raathigesh Your welcome. Majestic is a great app!

Here's a PR for the shortcut keys https://github.com/Raathigesh/majestic/pull/147

**Comment by M4cs** [comment]
Issue resolved in newest build! Great work @jsmey

**Comment by Raathigesh** [comment]
Released with 1.5.0 - https://github.com/Raathigesh/majestic/releases/tag/1.5.0
