### ISSUE TITLE
[Bug] show version of majestic running not correct

### ISSUE THREAD

**Issue by huyhqit** [Raathigesh/majestic#125]
## Is this a bug report or a feature request?

Please specify whether this is a feature request or a bug.

## Version Info

- Version of Majestic: 1.4.0
- Version of Jest: 24.5.0
- Version of Node: 10.5.2
- Operating System: Window 10

I ran `majestic --version` in a terminal, I got version 1.2.24
but in `packages.json`, version `1.4.0`

**Comment by Raathigesh** [comment]
Please test it with the latest version. This should be fixed.

**Comment by huyhqit** [comment]
This fixed in version `1.4.1`
