### ISSUE TITLE
Sticky header on Coverage page

### ISSUE THREAD

**Issue by FrediLehmann** [Raathigesh/majestic#140]
## Is this a bug report or a feature request?

feature request

## Version Info

- Version of Majestic: v1.4.1
- Version of Jest: 24.1.0
- Version of Node: v10.15.3
- Operating System: macOS Mojave 10.14.4

## Reproduction Repo

On the Coverage page the header should stay in position. Now if i scroll i lose the Row information (like statements, branches, lines etc.).

This section should stick on top:
![Screenshot 2019-05-07 at 11 07 30](https://user-images.githubusercontent.com/22279516/57287701-60182800-70b8-11e9-9020-9bc5d8425400.png)

**Comment by Raathigesh** [comment]
We embed the HTML file generated by Jest as an iframe so we can't do much in the way report behaves.

**Comment by Raathigesh** [comment]
I'm closing this. If you have ideas, please feel free to re-open.
