### ISSUE TITLE
Keyboard shortcuts conflict with browser controls

### ISSUE THREAD

**Issue by BuckAMayzing** [Raathigesh/majestic#150]
## Is this a bug report or a feature request?

Bug (debatable)?

## Version Info

- Version of Majestic: Latest
- Version of Jest: irrelevant
- Version of Node: irrelevant
- Operating System: irrelevant

## Reproduction Repo

ctrl-w is the current shortcut for watch mode. This is the button to close a tab in Chrome.
ctrl-s is the shortcut to for search. This attempts to save the page, and appears to cause a crash in Chrome.

etc...

I recommend changing the shortcuts to alt+[current key]. I'm not aware of any issues with those shortcuts.

I'm up for creating the PR unless there are objections.

**Comment by Raathigesh** [comment]
Please feel free to create a PR. I'm good with the suggestion. Also please do update the readme to reflect the change. Thanks.
