### ISSUE TITLE
Incorect key bindings

### ISSUE THREAD

**Issue by Gherciu** [Raathigesh/majestic#153]
Incorrect key bindings:

Expected:
alt+t - run all tests
alt+enter - run selected file

Result: 
ctrl+t - run all tests
ctrl+enter - run selected file
and ctrl+t doesn't work... this command opens a new tab in the browser (Google Chrome)

pls update Readme.md if you have made any change

## Version Info

- majestic: 1.5.0
- jest-cli: 24.7.1
- node:10.15.3
- os: windows

**Comment by Raathigesh** [comment]
We did change the binding but didn't do a release. With the new release, it should be right. https://github.com/Raathigesh/majestic/releases/tag/v1.6.0
