### ISSUE TITLE
How do I update a snapshot / where is the button?

### ISSUE THREAD

**Issue by IPWright83** [Raathigesh/majestic#156]
I read that there's a way to update snapshots for an individual test - how do I do this? I can't seem to find a button anywhere in the UI?

I'm hoping to use this to replace my dependance on WallabyJS as this UI is really nice. Well done :)

**Comment by Raathigesh** [comment]
If you have a failed snapshot in a test, there should be a button with the text"Update Snapshots" right next to the "Run" button.

**Comment by IPWright83** [comment]
I don't see that button... I'll rerrun, double check and get a screenshot of necessary

**Comment by Raathigesh** [comment]
A screenshot would be really helpful. This could be a bug or a regression.

**Comment by IPWright83** [comment]
Sorry for not getting back to you, yeah. Here's a screenshot of what I'm seeing.

<img width="1415" alt="Screenshot 2019-07-08 at 11 05 17" src="https://user-images.githubusercontent.com/1374775/60802247-66865700-a170-11e9-93ac-cc519801b16e.png">

**Comment by IPWright83** [comment]
Let me know if I can be of anymore help :) I'm really liking the UI and hoping with Jest watch mode that I can replace WallabyJS with this 👍

**Comment by Raathigesh** [comment]
Hey, Thank you for the screenshot. It is definitely a bug. I'll have a look into it soon and possibly fix it.

**Comment by ziofat** [comment]
Any update? I have suffered from this for a while.
![image](https://user-images.githubusercontent.com/8521174/62606350-9e7ae880-b92e-11e9-98c4-346cccbbb30b.png)

**Comment by jaredtmartin** [comment]
I'm having this issue too.  Any update?

**Comment by IPWright83** [comment]
@Raathigesh could you put some instructions together on debugging majestic? Maybe I can then take a look if I find any spare time...

**Comment by nfarina** [comment]
Having this button would be so useful! Currently I have to update via command line then re-run in Majestic.

**Comment by tohagan** [comment]
Not fixed yet?

**Comment by adamkleingit** [comment]
I opened a PR:
https://github.com/Raathigesh/majestic/pull/187
