### ISSUE TITLE
Wrap test file path to avoid hiding action buttons

### ISSUE THREAD

**Issue by vcpablo** [Raathigesh/majestic#159]
## Is this a bug report or a feature request?

Bug

## Version Info

- Version of Majestic: 1.6.0
- Version of Jest: ^24.8.0
- Version of Node: 10.16.0
- Operating System: macOS Mojave 10.14.3

## Reproduction Repo

As this is quite a simple bug, I did not create a specific repository with test codes to reproduce it. Basically, all it needs to be done is to include a CSS rule `word-break: break-all` in the component responsible for rendering the test file full path.
In this case, when the path is too big, the action buttons are not displayed.

## Without the CSS rule
![image](https://user-images.githubusercontent.com/4389464/61635407-e41a8e80-ac69-11e9-99d0-47a29f584e90.png)

## With CSS rule (edited using `Inspect` directly) 
![image](https://user-images.githubusercontent.com/4389464/61635436-f7c5f500-ac69-11e9-8ac7-8169be0084af.png)

**Comment by jsmey** [comment]
I can look into this

**Comment by Raathigesh** [comment]
@jsmey Thanks you!

**Comment by jsmey** [comment]
https://github.com/Raathigesh/majestic/pull/161

**Comment by gregveres** [comment]
@jsmey and @Raathigesh I don't think this is fixed. I am pretty sure that PR #161 was supposed to fix it but it still remains an issue. 

I don't think the OP's solution of breaking the path with word-break is the best approach. I put in a "flex-wrap: wrap" to the container and that seemed to do a better job. Once the left and right boxes don't have enough room, the buttons wrap to the next line. 

I would suggest adding 

```JS
  flex-wrap: wrap;
```
to line 30 of [index.tsx](https://github.com/Raathigesh/majestic/blob/master/ui/test-file/summary/index.tsx)

**Comment by gregveres** [comment]
The commit is over in my fork: https://github.com/gregveres/majestic/commit/0356052205bc55be41deaafefd65364b8427d3e0
