### ISSUE TITLE
Requires node to be installed globally

### ISSUE THREAD

**Issue by Haroenv** [Raathigesh/majestic#16]
## Is this a bug report or a feature request?

🐛 

Please specify whether this is a feature request 🎁 or a bug 🐛.

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 22.0.3
- Version of Node: (not installed globally), using nvm: 9.3.0 is the default
- Operating System: macOS 10.13.2

## Info

The "output" is `env: node: No such file or directory`

Maybe run `nvm use` in the directory if nvm is available?

**Comment by Haroenv** [comment]
I also have this issue in VS Code, so it might be related to node-pty instead of this 🤔

**Comment by Haroenv** [comment]
maybe https://github.com/Tyriar/node-pty/issues/112 ?

**Comment by peterschussheim** [comment]
I have this problem too using the same version info as Haroenv.

**Comment by lorderikir** [comment]
Yep, same problem for me.
Currently on Node v9.2.0 (npm v5.6.0)
macOS High Sierra (v10.13.2)

**Comment by Raathigesh** [comment]
I myself is not a nvm or mac user so I have to dig into this a bit to see what we can do. 

@Haroenv Running `nvm use` in the directory would make node available globally?

**Comment by zanza00** [comment]
I have the same problem, using also nvm.

I think that the correct command should be `nvm use default`

**Comment by Haroenv** [comment]
`nvm use` in the directory for that directory's nvm version (if it has `.nvmrc` in the directory or its parents). `nvm use default` will always pick the global version, which might not be the same as used in that folder

**Comment by zanza00** [comment]
`nvm use` without a `.nvmrc` doesn't work. it prints `No .nvmrc file found`.

I don't think there is a unique command of nvm that solve the problem, the best strategy would be to use `nvm use` if `.nvmrc` is present otherwise use `nvm use default`

**Comment by Haroenv** [comment]
`nvm exec jest` or `yarn jest` would work maybe?

**Comment by zanza00** [comment]
`nvm exec ...` should work, it falls back to the default `alias`

**Comment by gautamarora** [comment]
@Raathigesh - i ran into this problem as well with nvm, and can try to test the fix suggested above of running `nvm use`.

Will this be something that needs to be run on application start (and possibly be added to [Process.ts](https://github.com/Raathigesh/majestic/blob/master/app/src/renderer/util/Process.ts#L11) or is there another place in code where you think this should be added?

**Comment by LoicMahieu** [comment]
Just my 2 cents:
```sh
ln $HOME/.nvm/versions/node/v9.4.0/bin/node /usr/local/bin/node
```

**Comment by Raathigesh** [comment]
Hey guys,

If you would like to give majestic a try again, please take a look at the [Readme](https://github.com/Raathigesh/majestic).  Now majestic is shipped as an npm module.

@gautamarora Sorry, just now I noticed your question. Apologies.

**Comment by Raathigesh** [comment]
This should be fixed now with the rewrite so closing it for now.

**Comment by Haroenv** [comment]
Works as the nom module now 🚀

**Comment by Raathigesh** [comment]
That is very nice to hear 👍
