### ISSUE TITLE
How to switch to failing test or failing suites

### ISSUE THREAD

**Issue by ifrontend-xyz** [Raathigesh/majestic#160]
How to switch to failing test or failing suites .

**Comment by jsmey** [comment]
The failed tests button will show on the sidebar when there are failing tests. 

<img width="273" alt="Screen Shot 2019-09-03 at 9 09 11 AM" src="https://user-images.githubusercontent.com/10177710/64190173-9ed1ab00-ce2a-11e9-9fd5-656b5a7b93c2.png">

**Comment by ifrontend-xyz** [comment]
thank
