### ISSUE TITLE
Ability to setup Env vars for running tests

### ISSUE THREAD

**Issue by mrchief** [Raathigesh/majestic#17]
## Is this a bug report or a feature request?
🎁 Feature request

## Version Info
N/A

How does one specify env vars for running tests? I have npm scripts setup to initialise env vars before running tests like these:

```
  ...
  "scripts": {
    "test": "better-npm-run test",
  },
  "betterScripts": {
    "test": {
      "command": "jest --coverage",
      "env": {
        "LOG_LEVEL": "silent",
        "NODE_ENV": "test"
      }
    }
  },
  "jest" : { ... }
  ...
```
With majestic, I cannot set these in the UI since there is no such option and majestic seems to be not using the npm scripts.

**Comment by Raathigesh** [comment]
Currently it does not use the npm scripts. But certainly we can make a way to set the environment variables.   I would rather introduce a section called `majestic` in package.json and have the ability to set the environment variables there. Thoughts?

**Comment by mrchief** [comment]
You could but then I see 2 issues with that:

 - possible duplication of props: you have to declare and maintain same set of vars in 2 places since most projects _will have_ and _continue_ to keep the option of running via CLI (my `betterScripts` is one such example)

 - takes it further away from being zero-config

Most people have `npm test` or `yarn test` configured to run in a certain way. By hooking into that (assuming you have a way of doing that), **majestic**, _"instantly"_ becomes compatible with virtually every react project in the world. Zero config is the biggest selling point here - I'd suggest to keep it that way . 

Eventually, I do see the need of your own separate section but for this specific request, I wouldn't go that way.

**Comment by Raathigesh** [comment]
Good point! I've summarized an approach here https://github.com/Raathigesh/majestic/issues/23. That seems like a middle ground. Let me know what you think!

**Comment by mrchief** [comment]
@Raathigesh I'd still suggest to make the npm test script default and if not, then use `yarn jest` (or whatever majestic uses). I think the approach in #23 has it in reverse. 

That said, the config section in #23 is still minimal and doesn't require duplication of props/env vars setup so that's a good approach. 

In the end, the sensible default, IMHO, would be to pick `npm test` _first_ since that is the de-facto standard. I'm yet to find a react project that doesn't have a `npm test` script configured. :)

**Comment by Raathigesh** [comment]
What's scary about `npm test` is, it should be a minimal script with `jest --aditionalPams`. Otherwise if the test script contains anything extra like linting, majestic would break. This is because majestic provides extra args to the script.

**Comment by mrchief** [comment]
Oh I see. #23 it is then! :)

**Comment by Raathigesh** [comment]
As it turns out, running the npm script directly could cause some unintended behavior. For example, when there is a test failure, npm script would fail with a non 0 exit code. So this is the current implementation is, package json accepts a `runScript` property in the majestic sub-section.

Feedback is welcome.

```
{
   "majestic": {
        "runScript": 'jest --silent'
    }
}
```

Will have to introduce environment variables as well.

**Comment by Raathigesh** [comment]
This is addressed with the rewrite. https://github.com/Raathigesh/majestic#optional-configuration
