### ISSUE TITLE
Feature request: POSTMAN like view

### ISSUE THREAD

**Issue by goldbergyoni** [Raathigesh/majestic#172]
This is a feature request.

Just an idea - POSTMAN is super-popular for API testing. It's downside however is pushing toward manual work. Something changed? run all the routes again manually and don't forget anything.

Many people also code tests against APIs (super popular for backend Microservices), however the test runner and results are not centered around routes. What if Majestic had a POSTMAN-like view, that shows me all my API test by HTTP method & route so I can both understand which route fails and run it like in POSTMAN

This, however, demands some cooperation from the test writer - the title format, or maybe decorators, must provide this info in an agreed way.

Does this make sense? Does this feel within the project scope?

**Comment by Raathigesh** [comment]
Hi @goldbergyoni,

That's an interesting use-case but it looks like if we are to implement it, we also have to supply an SDK which allows the developers to write the tests in a certain way. Majestic's aim is to be a GUI for Jest with minimal or zero configuration and incorporating this specific use-case feels like majestic becoming more opinionated.

Can't these tests be structured using the nested `describe` and `test` methods along with snapshot assertions for the response?

I also feel a dedicated UI for this use-case could be super powerful and if you are curious to create one, feel free to fork Majestic or reach out to me if you need more details on the inner workings of Majestic.
