### ISSUE TITLE
Failed to open file in editor. You may need to install the code command to your PATH if you are using VSCode:  spawn code ENOENT.

### ISSUE THREAD

**Issue by TransmissionsDev** [Raathigesh/majestic#176]
## Is this a bug report or a feature request?

Bug Report

## Version Info

- Version of Majestic: Latest
- Version of Jest: 24.9.0
- Version of Node: v12.13.1
- Operating System: MacOS El Capitan

When I run `majestic` in this repo cloned to my machine (https://github.com/kentcdodds/js-mocking-fundamentals) and click one of the `open in editor` buttons, I see this error in the VS Code terminal: 

```
Could not open external-mock-module.js in the editor.
The editor process exited with an error: spawn code ENOENT.

Failed to open file in editor. You may need to install the code command to your PATH if you are using VSCode:  spawn code ENOENT.
```

Can anyone help with this, as I have a feeling this is user error on my part?

**Comment by Raathigesh** [comment]
Can you try executing the "[Install code command in Path](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)" from VSCode.

**Comment by TransmissionsDev** [comment]
> Can you try executing the "[Install code command in Path](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line)" from VSCode.

Fixed thank you!
