### ISSUE TITLE
Is there change majestic logo?

### ISSUE THREAD

**Issue by trustyoo86** [Raathigesh/majestic#177]
## Is this a bug report or a feature request?

Feature request

## Version Info

- Version of Majestic: 1.6.1
- Version of Jest: 24.9.0
- Version of Node: 8.9.4
- Operating System: Mac OS X

## Reproduction Repo

I want to use this testing tool in my company, But someone ask me that change majestic logo in sidebar. I thought that change logo option is useful for company test server. Could I pull request change logo using majestic option? 

Thank you.

**Comment by Raathigesh** [comment]
Sure
