### ISSUE TITLE
Windows Setup executable should not require elevated permissions

### ISSUE THREAD

**Issue by HipsterZipster** [Raathigesh/majestic#18]
## Is this a bug report or a feature request?

Bug

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 22.0.0
- Version of Node: 8.7.0
- Operating System: Windows 7

## Reproduction Repo

majesticsetup0.1.0.exe currently requires elevated permissions (UAC) in order to run. Is this necessary? Is there any way to generate an exe that doesn't require it? 

It's a blocker for many developers running in locked-down corporate environments that cannot freely install software that requires elevated permissions to run.

Thanks again and can't wait to try it out!

**Comment by Raathigesh** [comment]
Majestic uses https://www.electron.build/configuration/nsis for packaging. I understand your concern but I'm not quite sure whether the auto update would work without elevation. I'll have to check on this and get back.

**Comment by Raathigesh** [comment]
Next release not needs to be elevated 🎉 App installs per user and not per machine.

**Comment by Raathigesh** [comment]
This is shipped https://github.com/Raathigesh/majestic/releases/tag/v0.2.0
