### ISSUE TITLE
File structure is flat?

### ISSUE THREAD

**Issue by IPWright83** [Raathigesh/majestic#188]
**Bug**: The file structure doesn't seem to show indentation making it difficult to understand which file sits where.

## Version Info

- Version of Majestic: v1.6.2
- Version of Jest: v24.9.0
- Version of Node: v12.16.1
- Operating System: Ubutunu 18.04.4 LTS

## Reproduction Repo

1. Create a directory structure within your project
2. Run your tests with `majestic --app`
3. You expect to see the file tree with indentations to reflect subfolders

Instead all the folders are flat.

![image](https://user-images.githubusercontent.com/1374775/79326227-676fc480-7f0a-11ea-802d-91ab9281ad6e.png)

**Comment by Raathigesh** [comment]
This is a regression we introduced recently. Will try to fix it.

**Comment by Raathigesh** [comment]
Fixed in v1.7.0
