### ISSUE TITLE
Bug: Show Output popdown displays incorrectly

### ISSUE THREAD

**Issue by ScottEfird** [Raathigesh/majestic#20]
## Is this a bug report or a feature request?
This is a bug. 

## Version Info

- Version of Majestic: Version 0.1.0
- Version of Jest: : 20.0.4
- Version of Node: 6.11.1
- Operating System: Windows 10 Up to date

## Reproduction Repo
I have three monitors, if I open up the Show Output popdown I get this bug. Running the program not at full screen fixes it. Monitors are 2560 x 1440 with normal scaling. 
![capture](https://user-images.githubusercontent.com/11140326/34542425-298f0f52-f0a2-11e7-9dcc-d65366d8bb0e.PNG)

If it isn't clear in the picture, the app is running at full screen, the black bar is another program running at full screen on another monitor.

**Comment by Raathigesh** [comment]
That's unfortunate. I'm planning to move the console pane as a sliding panel to the right so it would be more convenient. I'll have a look.

**Comment by ScottEfird** [comment]
That might be a little bit better of a work flow too.

**Comment by Raathigesh** [comment]
This is how it would look going forward.

![image](https://user-images.githubusercontent.com/3108160/34563244-f980eab0-f1a5-11e7-8689-5017b99ecf3f.png)

**Comment by Raathigesh** [comment]
Fixed in release https://github.com/Raathigesh/majestic/releases/tag/v0.2.0
