### ISSUE TITLE
[Feature] Add an open project option to the top toolbar 

### ISSUE THREAD

**Issue by James-E-Adams** [Raathigesh/majestic#21]
![image](https://user-images.githubusercontent.com/9067274/34545414-f2a365c0-f140-11e7-8d39-748abea61ea3.png)
Maybe just left of `help`, it could be useful to have a way to open a project. I.e` File -> open project..`

**Comment by James-E-Adams** [comment]
As currently you have to close and reopen majestic to switch projects as far as I can tell.

**Comment by Raathigesh** [comment]
Yep. This workflow needs some serious improvement.

**Comment by James-E-Adams** [comment]
Coolio. Maybe I'll start with this on the weekend.

**Comment by James-E-Adams** [comment]
Working on this now. In `menu.ts`, I'm trying to bring in the workspace from store.
But when I call `workspace.openProject();`, it's erroring because Toaster wants the document available when the workspace is created. 

![image](https://user-images.githubusercontent.com/9067274/34632267-92f373e8-f2c8-11e7-8824-cade2066bd1b.png)

**Comment by James-E-Adams** [comment]
I wonder if the workspace store can be broken down, and some utility functions brought out. Seems a bit monolithic atm, and it may be hard to use a small part of it (like in this scenario.)

**Comment by Raathigesh** [comment]
This is because electron dont allows us to use the stuff from renderer directly from the main process. The stuff in the main folder are the once we can use on the main process. And menu is only available in the main process. We have to use the ipc module of electron to send a message to the renderer when the menu is clicked and then listen to the message from the  renderer.

**Comment by Raathigesh** [comment]
We should be able to do the below from main.ts
```
mainWindow.webContents.send('openProject');
```

and then in the renderer
```
import {ipcRenderer} from 'electron';

// probably this listen can be attached in the contructor of the workspace?
ipcRenderer.on('openProject', () => {
    // open project through workspace
});
```

https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md

**Comment by James-E-Adams** [comment]
Yup I was just reading up about that - it's just an EventEmitter, so shouldn't be to hard to hook up. Thanks for the snippet, will see how I go.

**Comment by Raathigesh** [comment]
Yep! Awesome 👍

**Comment by James-E-Adams** [comment]
Cool. Got it. Will open a PR now. :)

**Comment by Raathigesh** [comment]
Thanks James for the PR.
