### ISSUE TITLE
Majestic stops when a `it` is a `todo`

### ISSUE THREAD

**Issue by C0ZEN** [Raathigesh/majestic#212]
## Is this a bug report or a feature request?

Majestic does not handle the `.todo` for a `it` and just stops.
This is annoying and I do not see any usefulness of this.

## Version Info

- Version of Majestic: 1.7.0
- Version of Jest: 26.2.2
- Version of Node: 13.7.0
- Operating System: W10

## Reproduction Repo

- Create a test with `it.todo(``);`.
- Run Majestic.
- Majestic stops.
- Remove the test.
- Run Majestic.
- Everything is fine.

**StackTrace:**
```
return finalText.concat(`\`\$\{${path.node.arguments[0].expressions[currentExpressionIndex++].name}\}\``);
TypeError: Cannot read property 'name' of undefined
```

**Comment by rbarbazz** [comment]
After doing some testing it appears that any empty template will fail, for instance: `test(``)` or `it(``)`.

I can make a PR to address this.

**Comment by C0ZEN** [comment]
Still waiting for the PR to be merged.
@rbarbazz get the job done a while ago.
