### ISSUE TITLE
Check if a test script is available before running npm/yarn jest directly

### ISSUE THREAD

**Issue by James-E-Adams** [Raathigesh/majestic#23]
A lot of projects add flags to their jest calls under a script labelled `test` in their package.json. We should probably support this preferentially, and then default back to running `yarn jest` directly.

**Comment by Raathigesh** [comment]
This is a valid concern and also the same issue raised in #17.

What I'm thinking is to still have the current method, which is executing jest directly as the default but introduce a majestic subsection in package.json which takes in the name of the script that should be executed by majestic if specified.

```
{
    "scripts": {
        "customRunScript": "jest additionaparams moreParams"
    },
    "majestic": {
      "configFile": "path to config file" // This used to be outside before. Let's move it in here.
      "executionScriptName": "customRunScript" // If this is not specified, majestic will use the default
    }
}
```

This approach allows the simpler project, which does not need the custom script, to work out of the box but a complex project to take control of how majestic executes the tests.

I know the tagline says "Zero config" but this is a power user's use case.  If you ask me, Zero config actually means "sensible defaults" for trivial cases. The tool should be flexible enough for advanced cases and here that's what we are trying to do 😄 

Let me know what you think!

**Comment by James-E-Adams** [comment]
Yup. I like that approach. Zero config if your project isn't a unique 🌻, otherwise provide the option to wire it up correctly.

**Comment by Raathigesh** [comment]
As it turns out, running the npm script directly could cause some unintended behavior. For example, when there is a test failure, npm script would fail with a non 0 exit code. So this is the current implementation is, package json accepts a `runScript` property in the majestic sub-section.

Feedback is welcome.

```
{
   "majestic": {
        "runScript": 'jest --silent'
    }
}
```

**Comment by Raathigesh** [comment]
The rewrite would allow additional config options to be passed to jest if required. But it should be documented though!
