### ISSUE TITLE
Bug: Typo - Execution Summary "Test Suits" heading should be "Test Suites"

### ISSUE THREAD

**Issue by BrianSchroer** [Raathigesh/majestic#26]
bug 🐛

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: N/A
- Version of Node: N/A
- Operating System: N/A

## Info

In the Execution Summary section, the "Test Suite" heading is misspelled.

It looks like a simple fix to [test-summary.tsx](https://github.com/Raathigesh/majestic/blob/master/src/renderer/components/topbar/test-summary.tsx) is required:

`<span>Test Suites</span>`

**Comment by BrianSchroer** [comment]
I can submit a pull request to fix this if that's OK.

**Comment by Raathigesh** [comment]
Thank you for the PR. I suck at spelling things 😄
