### ISSUE TITLE
Error when run in projects that don't use git/hg

### ISSUE THREAD

**Issue by gricard** [Raathigesh/majestic#3]
## Is this a bug report or a feature request?

Bug 🐛

## Problem:

It seems like Majestic just runs 'jest --watch' in your project directory, but for projects that don't use git or hg, it displays an error:

```
--watch is not supported without git/hg, please use --watchAll
```

This is related to this issue: https://github.com/facebook/jest/pull/4737

Perhaps there should be an option to use --watchAll? Or, if you want to keep it zero-config, have it check for that error and re-try using --watchAll.

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 22.0.4
- Version of Node: 8.4.0
- Operating System: Win 7

## Recreatable repo
I can't make a repo because the bug won't occur in a git repo. It only occurs in projects that do not use git/hg.

**Comment by Raathigesh** [comment]
Oh snap! Did not know that --watch only works for a git-based project. I'll fix this.

If you want, you could turn off the watch mode via the toggle switch in the control bar for the time being but that's useless actually I guess :)

**Comment by Raathigesh** [comment]
This is fixed in the latest version.
