### ISSUE TITLE
Add electron-react-devtools automatically

### ISSUE THREAD

**Issue by James-E-Adams** [Raathigesh/majestic#33]
As discussed in the initial PR - still unsolved.

Aim: 

To avoid the step described in the readme, but only do it in development mode of course.

**Comment by James-E-Adams** [comment]
Ooo found this. https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md

exploring.

**Comment by James-E-Adams** [comment]
Weooo! Got it, with a hardcoded path. Now just to work out how to make it universal.

**Comment by Raathigesh** [comment]
Nice 😄

**Comment by James-E-Adams** [comment]
```javascript
app.on("ready", () => {
  mainWindow = createMainWindow();
  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();
  if (isDevelopment) {
    BrowserWindow.addDevToolsExtension(path.resolve(process.env.AppData,"../", `Local/Google/Chrome/User Data/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/2.5.2_0`));
  }
});
```
in `main\index.ts` but two things:

a) config for OS because this will only work for windows.
b) versions of react dev tools probably have different extension hashes.

This is probably not worth investing any more time in as now I've finished my coffee and should do something more productive. ☕️

**Comment by Raathigesh** [comment]
You are right. Let's put it on hold then. But thank you so much for digging into it 😃

**Comment by James-E-Adams** [comment]
Happy to be involved! On a similar note - I wanted styled components to show up nicely in the react dev tools, using https://github.com/styled-components/babel-plugin-styled-components. It should just work out of the box since here https://webpack.electron.build/add-ons it says it automagically adds any babel plugins/presets - but haven't had any luck.

**Comment by Raathigesh** [comment]
Did you try restarting the app? I can recall previously webpack electron was behaving strangely by not picking up the plugins 😞

**Comment by James-E-Adams** [comment]
I did 😢 .

**Comment by Raathigesh** [comment]
Dropped electron 😅
