### ISSUE TITLE
[todo] Set up CI

### ISSUE THREAD

**Issue by James-E-Adams** [Raathigesh/majestic#35]
Probably TravisCI, unless anyone has any strong opinions?

**Comment by Raathigesh** [comment]
TravisCI should be good. Travis supports linux and osx but I never tried majestic on a linux machine before. So should we go with osx? and Maybe later https://www.appveyor.com/ for windows.

**Comment by James-E-Adams** [comment]
@Raathigesh check out https://travis-ci.org/James-E-Adams/majestic

It doesn't have access to jest-editor-support. We have to come up with a way to bring in jest-editor-support without linking it.

**Comment by Raathigesh** [comment]
Npm does not have the latest always. We usually change things in jest-editor-support and make a PR to the jest repo. But jest-editor-support would be published only when jest is released. But currently we are using the latest version of jest-editor-support so let's remove the link for now and it should work.

**Comment by azz** [comment]
Did that in #37

**Comment by James-E-Adams** [comment]
Yup, beat me to the PR.

**Comment by azz** [comment]
🚤
