### ISSUE TITLE
Tests tree in sidebar includes tests that shouldn't be included

### ISSUE THREAD

**Issue by danielbrodin** [Raathigesh/majestic#41]
In my jest config I have set `roots` to `["<rootDir>/a/b/c/d"]` because I have all my tests from "d" and under, and there could be other tests that I do not want included from the other dirs.
My `testMatch` however is set to `"**/__tests__/**/*.test.(js|jsx)"` which I guess is the reason for some tests showing up in the tree structure under "Tests"?

I cannot however run those tests from majestic/jest since it doesn't match the active filter pattern.

So to be clear, the tree structure looks like this now.
```
rootDir
  /a
    /b
      __tests__/
        - do-not-show-me.test.js
      /c
        /d
          __tests__/
            - first.test.js
```

## Is this a bug report or a feature request?

bug 🐛.

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 22.0.4
- Version of Node: 8.9.2
- Operating System: MacOS

**Comment by Raathigesh** [comment]
This does seem like a bug. Is this a blocker for you?

**Comment by danielbrodin** [comment]
@Raathigesh absolutely no blocker, just wanted to inform you :)

**Comment by Raathigesh** [comment]
That's good news. Will try to address this in an upcoming release.

**Comment by Raathigesh** [comment]
@danielbrodin If you are keen, you could try the new alpha release of majestic rewrite. It suppose to be a lot better experience that before.
