### ISSUE TITLE
Pass custom parameters to node process

### ISSUE THREAD

**Issue by nfarina** [Raathigesh/majestic#43]
## Is this a bug report or a feature request?

🎁

## Version Info

- Version of Majestic: 0.2.0
- Version of Jest: 22.0.4
- Version of Node: 9.3.0
- Operating System: macOS 10.13.2

## Feature Request

I'm currently using the `async generator-functions` feature from Babel, which requires me to pass the flag `--harmony-async-iteration` to node.

When I run jest from the CLI, I must run it like this:

```sh
node --harmony-async-iteration ./node_modules/.bin/jest --config jest.config.json
```

I tried pasting this command into the `runScript` parameter for Majestic, but I believe Majestic is doing some "smart" parsing of that string which rearranges the Jest parameters incorrectly and passes them to the `node` process instead.

So in the Debug Console within Majestic, it prints out warnings like `Unrecognized option --json` etc.

It would be great if Majestic allowed passing custom parameters to node!

**Comment by Raathigesh** [comment]
Could you please share the exact string u provided to runScript ?

**Comment by nfarina** [comment]
It's the same one above:

```
node --harmony-async-iteration ./node_modules/.bin/jest --config jest.config.json
```

**Comment by Raathigesh** [comment]
Sorry, I missed that.  Right now the support for the custom script is very minimal.  The custom script allows you to pass additional parameters to Jest process but the script assumes the format would be something like `jest --aditionalParameterUserProvides` and then Majestic also appends some more parameters so It can do it's thing.

https://github.com/Raathigesh/majestic/blob/4732ec571bab3663bda2c800125d34c0e3bd79d7/app/src/renderer/util/Process.ts#L29-L38

This has to be improved to support your use case and would address them in a future release.

**Comment by cchabanois-sfdc** [comment]
I have a similar issue. I don't use jest directly but a wrapper that then run "node  [...] jest [...]"
jestwrapper [wrapper options] -- [additional jest options]

I could make it work with majestic (the new alpha version) : 
{
  "majestic": {
    "jestScript": "~/pathto/jest-wrapper -- "
  }
}
but I cannot debug tests : it debugs the jest-wrapper instead.
This is because I am supposed to use "jest-wrapper --debug -- " to debug the tests ...

**Comment by Raathigesh** [comment]
I see the issue here. Probably there should be a way to control the debug script as well.

**Comment by Raathigesh** [comment]
More info here https://github.com/Raathigesh/majestic#optional-configuration

**Comment by nfarina** [comment]
Hey nice! Wow, Majestic is looking really slick now. I love that using it is as easy as `npx majestic` and no setup is needed. Going to make this a regular part of my workflow!

**Comment by Raathigesh** [comment]
Thanks @nfarina. I agree this is a much better experience. Please feel free to raise any improvements Majestic could do to make the testing experience better either via github issues or via https://spectrum.chat/majestic
