### ISSUE TITLE
Bug: Not working on Windows 10

### ISSUE THREAD

**Issue by eliw00d** [Raathigesh/majestic#5]
## Is this a bug report or a feature request?
Bug report.

## Version Info
- Version of Majestic: 0.1.0
- Version of Jest: 20.0.4
- Version of Node: 9.3.0
- Operating System: Windows 10

When I load a project in Windows 10, nothing shows up and running tests is not possible. I loaded the same project in OS X and was able to see my directory tree and run tests.

**Comment by Raathigesh** [comment]
That's strange because my primary laptop is windows 10 and Majestic was developed and extensively tested on Windows. Would you be able to provide a bit more info on how the configuration looks? Maybe a small repo to recreate the issue would be really helpful.

**Comment by Zyst** [comment]
I also have an issue with this. The tests themselves can run if I click it manually, but the project tree/etc don't seem to work.

![Screenshot with no project tree functionality](https://user-images.githubusercontent.com/3832380/34543558-1da45a58-f0a7-11e7-91fe-18df2ae6e0ef.png)

The only thing that I can think of is that this project is lerna based, so that might be throwing the tool off? I am running just one of the packages though, so it shouldn't be the case, who knows.

**Comment by Raathigesh** [comment]
Would you please share how your jest config looks like?

**Comment by Zyst** [comment]
Something like so:

```json
  "jest": {
    "rootDir": "src",
    "collectCoverageFrom": ["**/*.{js,jsx}", "!**/node_modules/**", "!**/__jest__/**"],
    "coverageDirectory": "../test-reports/coverage",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
        "<rootDir>/__mocks__/file.mock.js",
      "\\.(css|scss)$": "<rootDir>/__mocks__/style.mock.js"
    },
    "snapshotSerializers": ["enzyme-to-json/serializer"],
    "testPathIgnorePatterns": ["/node_modules/"],
    "transformIgnorePatterns": ["/node_modules/(?!@aeris/)"],
    "unmockedModulePathPatterns": []
  }
```

**Comment by Raathigesh** [comment]
Same reason as https://github.com/Raathigesh/majestic/issues/10#issuecomment-354966014

Add `testMatch` pattern as a workaround for now. This would be fixed in the next release.

```
"jest": {
    "testMatch": [ '**/__tests__/**/*.js?(x)', '**/?(*.)(spec|test).js?(x)' ]
     // other configs
}
```

**Comment by Zyst** [comment]
Yep that was it! Sorry for the false signal there.

**Comment by Raathigesh** [comment]
No worries. I also noticed that you have a `coverageDirectory` configured and this would make the tool not to display the coverage reports in the `coverage` tab since majestic does not respect that setting but it should. It's a bug and should be fixed.

**Comment by Raathigesh** [comment]
@eliw00d Do you have any other info that would help us to look into this? Perhaps a screenshot of the error on the console (Help menu => Open Dev Console).

**Comment by eliw00d** [comment]
Upon loading the project I get the following error:
```
index.html:1 Uncaught (in promise) 
AssertionError {name: "AssertionError", actual: "", expected: true, operator: "==", message: "missing path"…}
actual
:
""
expected
:
true
generatedMessage
:
false
message
:
"missing path"
name
:
"AssertionError"
operator
:
"=="
stack
:
"AssertionError: missing path↵    at Module.require (module.js:496:3)↵    at require (internal/module.js:20:19)↵    at i (file:///C:/Program%20Files/Majestic/resources/app.asar/renderer.js:1:1675)↵    at c (file:///C:/Program%20Files/Majestic/resources/app.asar/renderer.js:1:2024)↵    at b (file:///C:/Program%20Files/Majestic/resources/app.asar/renderer.js:1:2641)↵    at it.loadTestFiles (file:///C:/Program%20Files/Majestic/resources/app.asar/renderer.js:3:6980)↵    at O.then (file:///C:/Program%20Files/Majestic/resources/app.asar/renderer.js:3:7610)↵    at <anonymous>"
__proto__
:
Error
```
So, nothing gets loaded. If I try to run tests I get this error:
```
Workspace.ts:150 Uncaught TypeError: Cannot read property 'start' of undefined
    at it.runProject (Workspace.ts:150)
    at onClick (panel.tsx:63)
    at HTMLUnknownElement.callCallback (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1338)
    at Object.invokeGuardedCallback (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1195)
    at Object.invokeGuardedCallbackAndCatchFirstError (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1209)
    at executeDispatch (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1432)
    at Object.executeDispatchesInOrder (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1454)
    at executeDispatchesAndRelease (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1969)
    at executeDispatchesAndReleaseTopLevel (C:\Program Files\Majestic\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1980)
```

**Comment by Raathigesh** [comment]
Hey @eliw00d,

You could try the rewrite of majestic, if you like. [It''s now shipped as an npm module with a bunch of improvements.](https://github.com/Raathigesh/majestic)
