### ISSUE TITLE
Majestic V1

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/majestic#50]
This is a plan to make majestic more awesome with version 1

## Decouple from electron

Extract the main UI and the main business logic as a core library and implement a thin communication adapter so it could be used to talk to electron via IPC messages.

## Majestic via npm

Electron is great but not everyone is a fan of it. Moving electron away from the core implementation would enable us to distribute majestic as an npm module. `npx majestic` would open the UI in the browser.
The CLI and the UI would use web sockets to communicate through the communication adapter from the core.

## A UI revamp

A lot could be done to make the UI better.

## Other improvements
- Support for multi projects
- Performance improvements in larger projects
- A lot of unit tests

**The goal of this re-write is to make Majestic a tool where everyone writing tests in jest would love to have next to them.**

Feel free to share your thoughts!

**Comment by daedalus28** [comment]
This sounds great - decoupling from electron would allow majestic to run in places where you don't actually have a desktop development environment (like in Cloud9 or other cloud IDEs)

**Comment by Raathigesh** [comment]
We are almost there. Take a look at the readme for instruction on how to use the alpha rewrite.
