### ISSUE TITLE
Error opening debugger (alpha client)

### ISSUE THREAD

**Issue by lukebatchelor** [Raathigesh/majestic#52]
## Is this a bug report or a feature request?

Bug

## Version Info

- Version of Majestic: 1.0.0.alpha
- Version of Jest: 0.20.4
- Version of Node: 8.9.0
- Operating System: MacOSX Sierra

## Reproduction Repo

Tried running this in the [bolt repo](https://github.com/boltpkg/bolt). When selecting a test file and hitting debug I get this message in my console

```
(node:78902) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): FetchError: request to http://localhost:9229/json failed, reason: connectECONNREFUSED 127.0.0.1:9229
(node:78902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ps stderr: Debugger listening on ws://127.0.0.1:9229/5733f978-d2d6-416d-ae8e-d5c81de99bf7
For help see https://nodejs.org/en/docs/inspector
```

When I hit it a second time, I get this message

```
ps stderr: Starting inspector on 127.0.0.1:9229 failed: address already in use
```

But it also opens the flag with the link correctly, interestingly.

I don't believe I have any other debuggers open, I'll investigate a bit more later.
Just raising here as an fyi

**Comment by Raathigesh** [comment]
We should try to find a free port and use it to open the debugger to be safe I guess

**Comment by Raathigesh** [comment]
Hey Luke,

With the recent rewrite, I decided to remove the debugger to keep the scope manageable. Sorry about that.
