### ISSUE TITLE
Issue when several tests with same name in the same file.

### ISSUE THREAD

**Issue by cchabanois-sfdc** [Raathigesh/majestic#53]
## Is this a bug report or a feature request?
Bug 🐛.

## Version Info
- Version of Majestic: 1.1.0

## Reproduction Repo
```
describe('parent1', () => {
  it('child1', () => {
  });
});
describe('parent2', () => {
  it('child1', () => {
  });
});
```
![image](https://user-images.githubusercontent.com/36440483/45210341-984c3a00-b28f-11e8-9c11-2642844e107f.png)

Looks like second 'child1' test never end (which is not the case) ...

**Comment by Raathigesh** [comment]
This is a known defect but thank you for reporting. We rely on the specific test names to apply the test results but we should do something smart to figure out when there are many with the same name.

**Comment by Raathigesh** [comment]
This is fixed and now the UI shows full hierarchy.
