### ISSUE TITLE
Watch mode not working

### ISSUE THREAD

**Issue by hoschi** [Raathigesh/majestic#54]
## Is this a bug report or a feature request?

Please specify whether this is a feature request 🎁 or a bug 🐛: bug

## Version Info

- Version of Majestic: 1.1.0
- Version of Jest: 23.5.0
- Version of Node: 8.9.1
- Operating System: linux

## Reproduction Repo

https://github.com/hoschi/yode

* Go to core packages: `cd packages/core`
* Run `majestic`
* Change a assertion in a editor, eg. line 22 `expect(result.functions).toHaveLength(0)` from 0 to 1

Expected: Tests were run again like in jests watch mode
Actual: Nothing happens

**Comment by Raathigesh** [comment]
Should be ok with the new release. Have a look again, please. Thanks.

**Comment by hoschi** [comment]
This still exists with the current version :disappointed:

**Comment by Raathigesh** [comment]
Could you please try again with the latest majestic. In your sample repository, one of the tests takes a while to execute after a change but it did execute.

**Comment by mcastre** [comment]
I am also experiencing this issue. I toggled the Watch mode and if i make changes to a file, nothing happens. I have to click on the Run button for an individual test in order to see the changes

Majestic version: 1.2.22
Jest version: 23.6.0
OS: MacOS

**Comment by Raathigesh** [comment]
I also felt that the `Toggle watch mode` button is confusing. It doesn't actually run the tests but passes the `--watch` flag whenever you run all the tests or a single file. We should rethink the UI of that button to make it clear.

**Comment by mcastre** [comment]
So if the --watch flag has been passed down, and you run subsequent tests, wouldn't it still watch for those new changes? What was the challenge of trying to implement and watch mode that works similarily to jest's watch mode?

**Comment by Raathigesh** [comment]
We use Jest watch mode as is and this is how the UI works with watch mode:

- First, toggle the watch mode button on
- Now if you run all the tests by clicking the `Run all` button,
    - All the files would be watched which is the equivalent of running `jest --watch`
- But if you click on the `Run` button of a single test file,
    - Only the selected file would be watched which is equals to running `jest --watch ./my/file/path.js`

There is nothing specifically challenging about implementing watch mode. I feel like we could do better with the UX.

**Comment by mcastre** [comment]
Ah ok, now its working as expected. Nice! I think the UX works as is, just needs some documentation on how to enable it correctly.

**Comment by kevinbarabash** [comment]
I was confused by this as well.  I feel like toggling the "watch mode" button should rerun the tests.
