### ISSUE TITLE
--app flag doesn't start a chrome window

### ISSUE THREAD

**Issue by hoschi** [Raathigesh/majestic#55]
## Is this a bug report or a feature request?

Please specify whether this is a feature request 🎁 or a bug 🐛: bug

## Version Info

- Version of Majestic: 1.1.0
- Version of Jest: 23.5.0
- Version of Node: 8.9.1
- Operating System: linux

## Reproduction Repo

https://github.com/hoschi/yode

* Go to core packages: `cd packages/core`
* Run `majestic --app`

Expected: Chrome starts in app mode showing majestic UI
Actual: 
```
core > majestic --app
Majestic v1.1.0
Zero config UI for Jest
```
Shows up but nothing happens.

**Comment by Raathigesh** [comment]
Do you have chrome installed?

**Comment by Raathigesh** [comment]
Is it still the same with the new version of majestic ?

**Comment by Raathigesh** [comment]
Majestic uses chrome launcher (https://www.npmjs.com/package/chrome-launcher) to launch.  Please try the new version of Majestic and reopen if this is still a problem.
