### ISSUE TITLE
Test failure context lines of code

### ISSUE THREAD

**Issue by rythos42** [Raathigesh/majestic#58]
## Is this a bug report or a feature request?
Feature request

## Version Info

- Version of Majestic: alpha
- Version of Jest: 2.1.1
- Version of Node: 11.4
- Operating System: Windows 10

## Reproduction Repo

Jest reports a bit of context for the test failure which I find very helpful, whereas Majestic only reports the stack trace. Wondering if the lines highlighted in yellow in my picture below could be included in the Majestic report?

![image](https://user-images.githubusercontent.com/937640/51200411-42774680-18ae-11e9-8785-554b4afae6a9.png)

**Comment by Raathigesh** [comment]
Unfortunately, the jest reporter doesn't send the code frame info. This needs a bit of investigation. I'll have a look
