### ISSUE TITLE
describe('name') not prepended on test name in Majestic test report

### ISSUE THREAD

**Issue by rythos42** [Raathigesh/majestic#59]
## Is this a bug report or a feature request?

Feature request

## Version Info

- Version of Majestic: alpha
- Version of Jest: 2.1.1
- Version of Node: 11.4
- Operating System: Windows 10

## Reproduction Repo
We use jest describe to group our tests, but this information doesn't appear to be captured in the Majestic test reporter. It has the test name, but isn't prepending the describe name.

![image](https://user-images.githubusercontent.com/937640/51204351-43ad7100-18b8-11e9-97ba-d1e9db52c44f.png)

**Comment by Raathigesh** [comment]
Hey,

We rewrote Majestic from scratch and it's now supports grouping by describe. Would you be able to give it a try? instructions are here: https://github.com/Raathigesh/majestic/tree/v2

**Comment by Raathigesh** [comment]
Closing this since this is fixed now. Feel free to reopen.
