### ISSUE TITLE
Feature Idea: brew cask install support 🎁 

### ISSUE THREAD

**Issue by fbartho** [Raathigesh/majestic#6]
I have a bootstrap script for new engineers on my project, and we install apps alongside our repo dependencies using `brew cask install <app-dep>`. It'd be neat if majestic supported this!

**Comment by Raathigesh** [comment]
I'll look into this 👍

**Comment by iamnapo** [comment]
(Awesome project 👏 )

Can I take a look at this?

**Comment by Raathigesh** [comment]
@iamnapo I'm glad that you find the project useful. Please do!
