### ISSUE TITLE
Re-order of file search results

### ISSUE THREAD

**Issue by rythos42** [Raathigesh/majestic#60]
## Is this a bug report or a feature request?

Feature request

## Version Info

- Version of Majestic: alpha
- Version of Jest: 2.1.1
- Version of Node: 11.4
- Operating System: Windows 10

## Reproduction Repo

Using the file search, I think it would make more sense to have the file with a name matching the search be at the top. I assume the other search results are files containing what I typed? 

![image](https://user-images.githubusercontent.com/937640/51216819-8bdd8b00-18da-11e9-926d-2d8687286811.png)

**Comment by Raathigesh** [comment]
The rewrite should show the correct order. Please have a look. If not, feel free to reopen.
