### ISSUE TITLE
grouping tests via describe

### ISSUE THREAD

**Issue by alxshell** [Raathigesh/majestic#61]
## Is this a bug report or a feature request?

feature request

## Version Info

Version of Majestic: alpha
Version of Jest: 22.2.1
Version of Node: 11.2
Operating System: mac OS X Mojave

## Feature Description

In jest you can group tests together using a describe block. It would be very handy and useful to represent this in majestic in the same way. Also it should be possible to run all the tests, that are inside that describe-block.

**Comment by Raathigesh** [comment]
Hey,

I rewrote Majestic from scratch and it's now supports grouping by describe. Would you be able to give it a try? instructions are here: https://github.com/Raathigesh/majestic/tree/v2

**Comment by alxshell** [comment]
Thx @Raathigesh that sounds really great. I'm afraid I am not working on that corresponding project anymore but I have informed my successors about the good news.

**Comment by Raathigesh** [comment]
Great. Thanks.

**Comment by nicostorl** [comment]
Hi @Raathigesh,

@alxshell 's successor here 👋 

Thank you for taking action here.

What we thought would be really handy is a "Run"-button for each level:
✔️ run on file-level: runs all tests in the file 
❌ run on describe-level: runs all tests within the describe 
❌ run on it/test-level: runs a single test

This helps if you are running long lasting tests, made a change and just want to rerun a single test/test group.

Currently I am doing this maually via `jest -t 'describeName'` or `jest -t 'testName'`.
 
![Screenshot 2019-03-22 at 09 20 17](https://user-images.githubusercontent.com/15437747/54809608-16988880-4c84-11e9-8b0f-9893a1c9a813.png)

**Comment by Raathigesh** [comment]
Hi @nicostorl 👋 ,

The main reason for removing the button from each level is to make things simple but if it adds value we could add it as an enhancement. 

Also, you could always add `it.only()` or [describe.only()](https://jestjs.io/docs/en/api#describeonlyname-fn) to the test/describe you want to run and jest will run only that even if you run the entire file. That would not work for you as an alternative?

**Comment by nicostorl** [comment]
Hi @Raathigesh,

that's a good point 😃 I guess this will make my developing-life easier as-well. 

If there are some non-developers that want to rerun just a subset of all tests it might add value but that's currently not the case for us.

**Comment by Raathigesh** [comment]
Hi,

I agree it could be useful to be able to run a single it or describe and I'll keep that in mind for future  :) 

I'll close this issue for now but feel free to open issues if you feel like things could be improved.
