### ISSUE TITLE
complete overview is being rerendered by running one single test

### ISSUE THREAD

**Issue by alxshell** [Raathigesh/majestic#62]
## Is this a bug report or a feature request?

bug

## Version Info

- Version of Majestic: alpha
- Version of Jest: 22.2.1
- Version of Node: 11.2
- Operating System: mac OS X Mojave

## Bug description

After a "run files"-test with multiple tests, successful tests become green and unsuccessful tests are becoming red.
If you rerun a "red" test for example, the complete view is being rerendered instead of just the single test. So all the other tests are resetted (becoming blue) and you loose overview about which tests were failing.

**Comment by Raathigesh** [comment]
This is fixed with the rewrite. https://github.com/Raathigesh/majestic/tree/v2
