### ISSUE TITLE
Unable to use custom parameters

### ISSUE THREAD

**Issue by erikleo** [Raathigesh/majestic#63]
We have a requirement to run our jest tests synchronously which requires the jest flag '-i'.  I tried using the runScripts attribute by adding this to package.json:

`  
"majestic": {
    "runScript": "jest -i"
}
`

But after I do this and run majestic, two things happen.
1. my tests are no longer visible in pane in the left-hand side. 
2. after clicking the run button, I get the error: 
**Error: Cannot find module 'C:\dev\my-project-name\undefined'**
Where my-project-name is the directory where my project is

I tried to reproduce on simple demo project and after adding the runScript I get the same error when trying to run.   If I continually hit F5 to refresh the page, the tests on the left pane sometimes show up and sometimes don’t.  (on the larger app they never show up)

Anyone know what is going on?  Am I missing something that will allow me to use the runScript attribute? 

## Version Info

- Version of Majestic: 1.1 (alpha)
- Version of Jest: 23.6.0
- Version of Node: 8.15.0
- Operating System: Win10

## Reproduction repo

https://github.com/erikleo/JestMajesticDemo.git

**Comment by Raathigesh** [comment]
This is properly addressed now with the rewrite.  The config would look like this

```
"majestic": {
    "args": [
      "--i"
    ]
  }
```

More detail here https://github.com/Raathigesh/majestic#optional-configuration
