### ISSUE TITLE
Node version >10 compatibility

### ISSUE THREAD

**Issue by AwadMaharoof** [Raathigesh/majestic#64]
## Is this a bug report or a feature request?

Please specify whether this is a feature request 🎁 or a bug 🐛.: Bug

## Version Info

- Version of Majestic: 1.1.0
- Version of Jest: 22.2.2.
- Version of Node: 10.14.1
- Operating System: Windows

I am attempting to get the project running locally but when I attempted to install the yarn packages it fails with an error because the upath package is incompatible with node 10.

![majestic](https://user-images.githubusercontent.com/3054523/52457563-7a596d00-2b80-11e9-8c0d-927d2d707712.png)

**Comment by Raathigesh** [comment]
Thanks for the report. After the rewrite, the engine field is no longer there in package.json so should be fine now.
