### ISSUE TITLE
Syntax errors aren't reported

### ISSUE THREAD

**Issue by ericclemmons** [Raathigesh/majestic#67]
## Is this a bug report or a feature request?

Bug

## Version Info

- Version of Majestic: v1.2.20
- Version of Jest: 24.5.0
- Version of Node: v10.13.0
- Operating System: macOS

## Reproduction Repo

I was attempting to make a sandbox, but `npx majestic` automatically opens a window, which doesn't work in that environment.

I'd recommend `npx majestic --open` for launching a window (print the server address by default), or `npx majestic --no-open` to prevent it.

Anyway, my project has a syntax error preventing the tests from even running, so this error appears in the console, but not in the UI:

```json
{
  "changeToResult": {
    "path": "/Users/eric/Projects/ericclemmons/back-to-the-fixture/example/__tests__/graphql.test.ts",
    "numFailingTests": 0,
    "numPassingTests": 0,
    "failureMessage": "  \u001b[1m● \u001b[22mTest suite failed to run\n\n    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):\n    \u001b[96msrc/index.ts\u001b[0m:\u001b[93m5\u001b[0m:\u001b[93m29\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2552: \u001b[0mCannot find name 'Recorder'. Did you mean 'recorder'?\n\n    \u001b[7m5\u001b[0m export const recorder = new Recorder();\n    \u001b[7m \u001b[0m \u001b[91m                            ~~~~~~~~\u001b[0m\n",
    "testResults": [],
    "consoleLogs": null,
    "__typename": "TestFileResult"
  }
}
```

<img width="1188" alt="Screen Shot 2019-03-26 at 7 14 37 PM" src="https://user-images.githubusercontent.com/15182/55045567-6e741e00-4ffb-11e9-83bd-d1e6201688d5.png">

**Comment by Raathigesh** [comment]
I think it makes sense to open by default (or maybe this could be just my personal preference) so I'll go with a `--no-open` flag to prevent it for now.

Oh, I see, I totally ignored the top-level errors. I'll get that fixed.

**Comment by Raathigesh** [comment]
Added a `--noOpen` flag to prevent automatically opening the URL and also now the UI shows failure messages.

![image](https://user-images.githubusercontent.com/3108160/55070315-1829dc80-50da-11e9-9983-c69f59f7b35e.png)

Released so an `npx majestic` should do it.

Closing it for now.
