### ISSUE TITLE
Support for Angular testing?

### ISSUE THREAD

**Issue by pertrai1** [Raathigesh/majestic#7]
## Is this a bug report or a feature request?

**Feature Request**: Does this work with other frameworks? Looks like a good app, and will download once I know if I can configure it for running tests with Angular.

**Comment by Raathigesh** [comment]
If you write your tests with [Jest](https://facebook.github.io/jest/docs/en/testing-frameworks.html#angularjs), Majestic should work. But I never tested with an angular project so feel free to try out and let me know. I would love to help to make it work.

**Comment by pertrai1** [comment]
@Raathigesh  - I will give it a test run and let you know the results.

**Comment by keplersj** [comment]
This should help. https://github.com/thymikee/jest-preset-angular

**Comment by Raathigesh** [comment]
@pertrai1 As far as you get jest to work with angular, Majestic should work. I'm closing this for now but feel free to re-open if you see an issue where Jest works but majestic doesn't.

**Comment by zalos** [comment]
Hey @Raathigesh, Project is awesome, hopefully I'll get some time myself to have our team contribute. That said, im working with NRWL NX, and in particular angular. 

Given that, my tests pass in normal NRWL NX / NG Test, but fail in majestic. Im looking to use preset shown above, etc, but not really getting anywhere. I'm going to play around with it a bit more, but if anyone else is working on this as well, I wouldn't mind the company

**Comment by Raathigesh** [comment]
@zalos If you create a very simple repo, I could help to look into it as well.

**Comment by jarrodmedrano** [comment]
I'm using jest + majestic in angular and it works great
