### ISSUE TITLE
[Bug] Output View Doesn't Scroll

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#71]
## Is this a bug report or a feature request?

Please specify whether this is a feature request or a bug.

## Version Info

- Version of Majestic: 1.2.20
- Version of Jest: 20.0.3
- Version of Node: 8.15.1
- Operating System: 10.14 MacOS Mojave

## Reproduction Repo

Run majestic and run your tests. Once run if you have multiple outputs from a test you cannot scroll down to read them completely. Can't provide GH repo since It's a private source for my company.

My majestic op conf:
```
"majestic": {
    "args": ["--env=jsdom", "--config jest.conf.json", "-u"],
    "env": {
      "NODE_PATH": "src"
    }
```

**Comment by Raathigesh** [comment]
Could you please attach a screenshot? Also please give it a shot with the latest version. Yesterday we did fix an overflow issue.

**Comment by M4cs** [comment]
1.2.24 Seemed to Fix the issue. Good work 👍
