### ISSUE TITLE
Feature request: Coverage integration

### ISSUE THREAD

**Issue by culshaw** [Raathigesh/majestic#72]
Great project

It would be amazing to integrate this with the output of Istanbul to determine coverage too!

**Comment by Raathigesh** [comment]
Hey, We could easily show the overall code coverage in the sidebar. Are you interested in coverage for each file or overall ?

**Comment by pjnovas** [comment]
first of all ... thanks for this tool!

So, what I normally do is I work with test watcher doing TDD and when I finish the feature I check the total coverage, if is not at what I expect I then check which are the files low.
I think a full overage would be good and then an specific one to identify which is the one that needs attention.

**Comment by rkulla** [comment]
I like the idea of how `jest --coverage` works now where it's a summary at the bottom, but then you can open the full coverage report to get more info. Heck, i'd even be happy if this just linked or embedded  coverage/lcov-report/index.html

**Comment by Raathigesh** [comment]
We could easily show the coverage summary on the sidebar and probably will start there and enhance further.

**Comment by blackjackkent** [comment]
I would like to second this request. I'm really loving this tool so far but being able to integrate my coverage info as well would be very helpful. Specifically, I'd agree with @rkulla 's suggestion about linking to the output report. (Would also be nice if you could specify different jest configs when starting majestic; I use one for just testing and then one for testing with coverage.)

**Comment by wsrast** [comment]
I'll throw my hat into the ring for the `jest --coverage` behavior. That's the only thing that's keeping me from ditching the command line jest interface for this. Really great job on this, guys!

**Comment by Raathigesh** [comment]
Coverage integration is coming along nicely.

![image](https://user-images.githubusercontent.com/3108160/55477280-699b1400-5664-11e9-8419-82dd1bb5d774.png)

**Comment by Raathigesh** [comment]
Shipped 1.3 with coverage support. Give it a try! https://github.com/Raathigesh/majestic/releases/tag/v1.3.0

**Comment by aantipov** [comment]
Can't see it in the 1.3.0 :( Looks like dist files were not updated in the 1.3.0 release https://github.com/Raathigesh/majestic/issues/116

**Comment by Raathigesh** [comment]
You have to toggle the "Collect coverage" button to see the coverage. Dist files are up to date. I replied to the other issue with the reason for the wrong version.
