### ISSUE TITLE
Long file names break styling and overlap with other file items

### ISSUE THREAD

**Issue by yurm04** [Raathigesh/majestic#73]
## Is this a bug report or a feature request?
Bug

If the sidebar is not wide enough to fit the file structure horizontally, longer file names break the styling and overlap with other file items above/below.

<img width="147" alt="broken-file-item" src="https://user-images.githubusercontent.com/4642404/55099524-3d94f700-5096-11e9-897b-f9927f769eff.png">

## Version Info

- Version of Majestic:  `v1.2.22`
- Version of Jest: `21.2.1`
- Version of Node: `v8.11.2`
- Operating System: `macOS 10.14.4`

## Reproduction Repo

Unable to provide GitHub repo where bug was discovered (private repo).

**Comment by yurm04** [comment]
I opened PR https://github.com/Raathigesh/majestic/pull/75 to address this issue by following the VSCode convention of obscuring the longer filenames with ellipsis (`...`)

**Comment by Raathigesh** [comment]
Thank you for the PR. Appreciate it.
