### ISSUE TITLE
`opn` is not webpack friendly

### ISSUE THREAD

**Issue by gavinhenderson** [Raathigesh/majestic#76]
## Is this a bug report or a feature request?

This is a bug report

## Version Info

- Version of Majestic: 1.2.22
- Version of Jest: 24.1
- Version of Node: 11.12
- Operating System: Ubuntu 18.10

## Reproduction Repo

If you are not on `darwin` or `win32` then opn runs the following line https://github.com/sindresorhus/open/blob/master/index.js#L72

The indicated line is not webpack friendly and it leads to the following error

```
(node:23507) UnhandledPromiseRejectionWarning: Error: spawn /usr/lib/node_modules/majestic/dist/server/xdg-open ENOENT
```

## Possible Solution

My possible solution would be to add the xdg-open script to this repo and then copy it into dist using the webpack CopyPlugin which is already used.

If you are happy with this solution I can open a PR

**Comment by Raathigesh** [comment]
If we not bundle `opn` by marking it as [external](https://github.com/Raathigesh/majestic/blob/master/scripts/webpack.server.config.js#L52), would it fix the issue?

**Comment by gavinhenderson** [comment]
@Raathigesh I didn't know about webpack externals until right now. Yeah that would solve the problem! As well as having it as an external it needs to be moved to `dependencies` rather than `devDependencies` right? 

Want me to submit the PR or is it easier for you to fix it?

**Comment by Raathigesh** [comment]
Yes we have to move it to `dependencies` and I just noticed that `opn` is deprecated and the same package is available as [open](https://yarnpkg.com/en/package/open) so probably we should use that.

If you could create a PR, that would be appericiated since you can test it in Ubuntu after the fix.
