### ISSUE TITLE
regex problem running single test

### ISSUE THREAD

**Issue by Alaev** [Raathigesh/majestic#8]
## Is this a bug report or a feature request?

it's a bug 🐛.

## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 22.0.4
- Version of Node: 9.1.0
- Operating System: OSX

## Bug on running single test

At the moment looks like the regex exp is not working when clicking the single test run button

![screen shot 2018-01-03 at 10 23 08](https://user-images.githubusercontent.com/3925474/34513286-489ab4e6-f070-11e7-8fbc-b28b8c2efdfa.png)

Looking the problem the regex `^should return error 404$` is not working did try to run it on `jest-cli` when I run it `should return error 404` it works without problem

`jest-cli`

 ### with Regex - fail
![screen shot 2018-01-03 at 10 27 39](https://user-images.githubusercontent.com/3925474/34513394-c897d34a-f070-11e7-984c-70adb724daf7.png)

### witout Regex - pass
![screen shot 2018-01-03 at 10 29 18](https://user-images.githubusercontent.com/3925474/34513453-04716688-f071-11e7-8976-5814c2069e42.png)

**Comment by Raathigesh** [comment]
Thank you for such a detailed report. I'm aware of this issue but couldn't find time to pinpoint the exact reason for it yet. I'll take a look soon.

**Comment by Raathigesh** [comment]
Oh! Are you saying it fails even in the CLI with regex?

**Comment by Alaev** [comment]
@Raathigesh Yep, I think they are doing the regex in the background so there is no need to add `^$` Great app loved how you utilized react and mobx :)

**Comment by Raathigesh** [comment]
I'll have a look again. Glad you like the project. React and Mobx is really fun to work with.

**Comment by Raathigesh** [comment]
Removing the regex fixes the issue.
