### ISSUE TITLE
[Bug] Open in Editor returns ENOENT

### ISSUE THREAD

**Issue by M4cs** [Raathigesh/majestic#84]
## Is this a bug report or a feature request?

🐛 Bug Report

## Version Info

- Version of Majestic: 1.2.24
- Version of Jest: 20.0.3
- Version of Node: 8.15.1
- Operating System: 10.14 MacOS Mojave

## Reproduction Repo

Due to this being used in a professional atmosphere I cannot provide the repository that I'm using this with.

To Reproduce:

- Press the Open In Editor Button
- Spawning an Editor results in ENOENT

I believe this is due to no path being passed into openInEditor() and no configuration available for this path to be passed. 

Possible Fixes:

Add a config variable for path to Editor?
Find known code editors and display options, store choice?

**Comment by Raathigesh** [comment]
We use https://github.com/yyx990803/launch-editor to launch the editor. Could you try setting the `EDITOR` environment variable so the package would use that to launch the editor?

**Comment by M4cs** [comment]
It does try to open VSCode by default in the query. I can try to force set the env. Does "code" still work on macOS?

**Comment by Raathigesh** [comment]
`code` is hardcoded and it should work in mac if you set the `EDITOR` env variable in your terminal (not in majestic config).

But we should have the editor configuration rather than hardcoded.

**Comment by M4cs** [comment]
Open Command Palate in VSCode and type in Shell Command > Install command line 'code' to PATH. Then the code shortcut will work.
