### ISSUE TITLE
Unable to run tests - Cannot find module

### ISSUE THREAD

**Issue by ChrstnDmbchr** [Raathigesh/majestic#88]
Hi, I am currently having an issue trying to use your tool in a windows environment. The application loads fine and I can see the full test file tree however when trying to run any test I get the following error:

![image](https://user-images.githubusercontent.com/26926783/55226958-25e07e80-520e-11e9-96b2-c005a573debd.png)

The package has been installed globally on my machine. Issue appears to be the space in my User folder 'Christian Dambacher'. The application cannot seem to reference back to my app data which has the majestic folder for the module because of this. 

## Version Info

- Version of Majestic: v1.2.23
- Version of Jest in project: 24.0.0
- Version of Node: v8.11.4
- Operating System: Windows 10

**Comment by Raathigesh** [comment]
Hi 👋 

Could you please run majestic with the `--debug` flag so we could see where this is failing exactly?

**Comment by ChrstnDmbchr** [comment]
👋

Attached is where it fails.

![image](https://user-images.githubusercontent.com/26926783/55228492-211dc980-5212-11e9-9f55-2faaa66e3628.png)

**Comment by briwa** [comment]
@ChrstnDmbchr Hey, I have a slightly similar issue, but not sure if this applies to yours. Can you try rename your folder `C:\Users\Christian Dambacher` to something that doesn't contain spaces? I assume the space was the culprit.

**Comment by ChrstnDmbchr** [comment]
@briwa this does not fix my issue. I have made the same changes in my local repo that you have made as part of your PR however this did not work. I cannot change the folder name as this is my user profiles folder.

**Comment by briwa** [comment]
@ChrstnDmbchr Yeah, then my guess is that it is a separate issue, more Windows-related. You can reopen this perhaps.
