### ISSUE TITLE
Feature request: Parsing test.todo()

### ISSUE THREAD

**Issue by agustif** [Raathigesh/majestic#95]
Since Jest implemented .todo it would be nice to show one's todo's in majestic.

https://jestjs.io/docs/en/api#testtodoname

On the UI part
maybe showing it in a new Todos view after Tests, or maybe integrate it and display a different icon for todo tasks as unimplemented tests that are skipped.

Just an idea anyway, loving the project and great naming which helps remember to use it!

**Comment by Raathigesh** [comment]
That's indeed a nice to have. Will add it to the roadmap.

**Comment by culshaw** [comment]
Yep, this + the coverage is the only things stopping me ditching command line.

Great work!!!

**Comment by agustif** [comment]
I would love to help implement it if you think it can be easily done without much work needed to coordinate with the rest of the codebase. (So it makes sense for an external contributor to chime in without being a disturbance or making a mess out of a PR

Or maybe i can just propose a couple UI options for it if you would prefer, and leave the code implementation to you.

**Comment by Raathigesh** [comment]
It would be awesome if you could help out. [The inspector ](https://github.com/Raathigesh/majestic/blob/master/server/services/ast/inspector.ts)is responsible for reading the test spec. Let me know if I could help with anything else.

**Comment by agustif** [comment]
Sure @Raathigesh just can I get some help on the best way to run my own local version of majestic? I don't see nothing on the readme about cloning this repo/compiling/using own compiled version

Thx!

**Comment by agustif** [comment]
I got stuck at the sidebar/summary, not sure how to create the EVENT of numTodoTests

but looking good so far

<img width="909" alt="Screenshot 2019-04-03 at 00 41 51" src="https://user-images.githubusercontent.com/6601142/55440906-6abb3b00-55a9-11e9-8004-ff50b476bf1f.png">

**Comment by Raathigesh** [comment]
Hey 👋,

I don't think we want to show todo items on the sidebar.  Just listing them on the selected files would be enough right?

**Comment by agustif** [comment]
> Hey 👋,
> 
> I don't think we want to show todo items on the sidebar. Just listing them on the selected files would be enough right?

Yeah, probably, but I thought i'd be cool in case one doesn't know where the todo's are, to show total todo's count on the sidebar-summary, and maybe also add a Todo's icon on the sidebar's file which contains them?

![MGroup 2](https://user-images.githubusercontent.com/6601142/55442999-48c5b680-55b1-11e9-91d0-a4eb8e456ae9.png)

**Comment by Raathigesh** [comment]
Currently, we don't read all the test files upfront instead we just read the currently selected file and parse so it wouldn't be possible to know beforehand which files contain todo items.

It would be nice to show todo items but maybe, for now, we could go with showing for the selected file and now on the sidebar?

Reading all the files, listening to their changes and keeping the files in sync is a lot of overhead and would introduce instability and that's the reason we just go with the parsing only the selected file.

**Comment by agustif** [comment]
> Currently, we don't read all the test files upfront instead we just read the currently selected file and parse so it wouldn't be possible to know beforehand which files contain todo items.
> 
> It would be nice to show todo items but maybe, for now, we could go with showing for the selected file and now on the sidebar?
> 
> Reading all the files, listening to their changes and keeping the files in sync is a lot of overhead and would introduce instability and that's the reason we just go with the parsing only the selected file.

Agreed, opened a PR with my progress so far

**Comment by Raathigesh** [comment]
Thank you @agustif for the PR 👍  This is released with 1.3 so closing.
